### ISSUE TITLE
help on setting up default values/angular

### ISSUE THREAD

**Issue by jjarrell56** [fooloomanzoo/datetime-picker#30] opened 2018-01-16 20:23 UTC
I'm working with angular4x with Polymer2x. I am using typescript

I'm not catching on to how to set up an initial value for a date picker.

This is the property that I want bind to, to set the initial value in a date-picker
```
mydate: string = "2014-02-10" ;  // Iso8601 as string, as indicated in docs (feb 10, 2014)
```
when I use this, it appears to work but it is one day off, it gives me 2014-02-09.

What I really want to use is the `<overlay-date-picker>`.  I've tried all of these alternative solutions to no avail. It just uses today's date as the default value.

```
  <overlay-date-picker class="custom" [value]="mydate" with-backdrop no-overlap></overlay-date-picker>
  <overlay-date-picker class="custom" value="{{mydate}}"  with-backdrop no-overlap></overlay-date-picker>
  <overlay-date-picker class="custom" [date]="mydate" with-backdrop no-overlap></overlay-date-picker>
  <overlay-date-picker class="custom" date="{{mydate}}"  with-backdrop no-overlap></overlay-date-picker>
```
Note, these do not have the event binding when the UI changes to push the updated value to the model (this does work, so i've omitted for clarity).

Should I be using date or value?  What am I missing?

**Comment by fooloomanzoo** [comment] 2018-01-16 22:22
There were a lot of changes relating default values in the last week. Have you updated your elements to the newest versions? Just to check:
- datetime-picker should be `>2.5.8`
- number-input should be `>1.3.3`
- property-mixins should be `>1.0.12`
Because I can not reproduce your mistake. In the [demos ](https://fooloomanzoo.github.io/datetime-picker/components/datetime-picker/component-page.html#/elements/datetime-picker/demos/demo/datetime-picker.html) are also examples now, of elements with preset values.

**Comment by jjarrell56** [comment] 2018-01-16 22:29
That's what I want to hear.  Will try it out tomorrow.  ;)

**Comment by jjarrell56** [comment] 2018-01-17 19:10
Updated appears to have solved most of the problem.  I'm still losing one day on one of my inputs, I suspect it has something to do with timezone.

This is what I am binding to, the lodate, results in `12/31/2015` while the hidate correctly results in `12/01/2017`.  I have tried various flavors of adding time/with timezone off sets to the string, then it reverts to the bad, where it uses the current date as the default.
```
const params = new TwoDateParams();
    params.lodate = "2016-01-01" ;
    params.hidate = "2017-01-01" ;
```

**Comment by fooloomanzoo** [comment] 2018-01-17 21:22
Timezone is set automatically to the local timezone and is currently not changeable. It is also not included in the `datetime`- or the `time`-attribute. But I can not reproduce your problem, please have a look at [https://codepen.io/fooloomanzoo/pen/RxqNOb](https://codepen.io/fooloomanzoo/pen/RxqNOb)

**Comment by jjarrell56** [comment] 2018-01-19 19:34
I looked at yours, all good. My turn now.  I'm getting slightly different behavior from my app. In my app it was mostly working, but my app is one rev behind angular (4.x vs 5.x) and the typescript versions are slightly different than current.

So I used the angular-cli to generate a new stub project and put an example of what I am doing.  This sample has angular 5.x and a different version of typescript.  You will notice, I'm not getting default values but when I open the pull down, I do have the right value.  I am using a slightly hackish setTimeout but I can use a later angular lifecycle event.

Here is my sample repo.  https://gitlab.com/oldprogrammerio/datetimedemo.git

You will need to install angular-cli to run it (and do normal npm install and bower install).  
```
npm install @angular/cli -g
npm install
bower install
ng serve
```

I like your work and appreciate any help you can provide. ;)

**Comment by fooloomanzoo** [comment] 2018-01-19 20:55
I am not familiar with angular. But the first look at [two-dates.component.html](https://gitlab.com/oldprogrammerio/datetimedemo/blob/master/src/app/controls/two-dates/two-dates.component.html) raises a question: could it be that in angular the attribues must also be in **kebab-case** to be set? You try to set **autoConfirm**, but it might not be set. Thats why the picker is set to your preset date but the input is automatically generated to the date of today. If the picker is not autoConfirm and you close it with out confirming by pressing the arrow, it will be reset to the confirmed-date attribute (what should be in case you don't want it to be autoConfirming, the correct attribute to bind to).

**Comment by fooloomanzoo** [comment] 2018-01-19 22:00
But there might have been a minor bug for initial values, i fixed in the newest version

**Comment by jjarrell56** [comment] 2018-01-19 22:35
no, you were correct. the casing was wrong. this follow works and I don't need to defer the assignment.

```auto-confirm="true"```
I have to admit, i'm not completely clear on what angular is doing, your docs have it cased differently.  No worries though I'm happy it's working.  thank you.

**Comment by fooloomanzoo** [comment] 2018-01-20 00:16
But Angular-syntax is different to Polymer's databinding-syntax. Polymer transforms the internal used camelCase-style variables to attributes in kebab-style

**Closed by fooloomanzoo** 2018-01-20 00:16 UTC
